//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarmPress
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarmReshapeParam
    {
        public string BandSerial { get; set; }
        public System.DateTime ProcessedOn { get; set; }
        public Nullable<System.DateTime> LoadStartTime { get; set; }
        public Nullable<System.DateTime> PressStartTime { get; set; }
        public Nullable<System.DateTime> UnLoadStopTime { get; set; }
        public Nullable<System.DateTime> PressStopTime { get; set; }
        public Nullable<int> TopFixtureTemp { get; set; }
        public Nullable<int> BottomFixtureTemp { get; set; }
        public string TossingItem { get; set; }
        public Nullable<bool> ZHeightCheck { get; set; }
        public Nullable<bool> WarmPressCheck { get; set; }
    }
}
